### ISSUE TITLE
layout issue

### ISSUE THREAD

**Issue by farfromrefug** [sourcelair/xterm.js#596]
I am implementing xtermjs inside our apps.
I use it in react using a [npm package](https://github.com/farfromrefug/react-xterm) i emplemented 
I use it in 2 different use cases:

* a remote ssh console
* a log viewer (to get ansi colors)

The first use case works great. My only issue is taht i can't select text, but i think it's on my side
On the log viewer i have a layout issue that i don't understand,
I use ```xterm.write``` to write logs that i get through ```util.format``` and ```console.log```
So i write an already formated string. Sometimes even only the full content of our log file.
I get something like this
<img width="810" alt="screen shot 2017-03-14 at 14 15 08" src="https://cloud.githubusercontent.com/assets/655344/23902402/45c66130-08c1-11e7-951d-e458eec3aa25.png">
It seems to add spaces until it gets to a new line.

Any idea on what my cause this? Again it works perfectly well in my ssh remote console where i call ```xterm.write``` on the data received from ``ssh2```. That's why i am quite lost.

Thanks

**Comment by Tyriar** [comment]
It looks like either xterm.js or your pty process thinks the terminal is 1 character wide, how are you setting their dimensions?

**Comment by farfromrefug** [comment]
I use ```fit``` [within](https://github.com/farfromrefug/react-xterm/blob/master/src/react-xterm.tsx#L108) my react addon. But i just realized  i might be "desinchronized" between the ```fit``` and the ```resize```. I will test and report back.

**Comment by farfromrefug** [comment]
Ok so thanks to you i found a resize issue that i fixed. Now i am sure xterm have the correct number of rows/cols.
I then have what i think is my real layout issue now. I am almost sure it is due to tabs and spaces. 
The string i send is:
```
[SUCCESS] result for' 'GetComputeParams' { useWorkers: false,
  saveLoc: '/var/local/neose_server/data/captures',
  spotfileid: '1481186369750_00000000b7da9ebb',
  nb: 5,
  dynamic: { nbBefore: 2, nbBetween: 8 },
  maxRecords: 2,
  enableCleanupData: true,
  tetm: false,
  lcswait: 500,
  pumpPower: 30,
  camera: 
   { colorMode: 6,
     exposure: 50,
     pixelClock: 5,
     frameRate: 1,
     displayMode: 1,
     binning: 1,
     subsampling: 1,
     gain: 100,
     gamma: 100 } }
```
It is indented by ```util.inspect```
<img width="826" alt="screen shot 2017-03-15 at 09 36 54" src="https://cloud.githubusercontent.com/assets/655344/23939913/23a48224-0963-11e7-975d-dcec9799b745.png">
Do you see something obvious?

**Comment by jerch** [comment]
@farfromrefug Looks like you are sending the output directly to the emulator without any pty in between. Therefore your data is missing the pty rewrites like marking the line endings with '\r' and such.

A hacky fix would be to replace all '\n' with '\r\n'. Note that this will still fail for terminals with different dimensions than the orginal one the output got recorded in. To get support for this you will have to emulate the pty as well.

**Comment by farfromrefug** [comment]
@jerch thanks a lot that's what i was not understanding. I thought it could send it right away.
Will look at this. This answers that issue

Thanks
